### ISSUE TITLE
Dijkstra's korte pad algoritme exam

### ISSUE THREAD

**Issue by dcswitzer** [HAN-ASD-DT/exam-2018-2019#1]
@dvberkel The adjacency list doesn't correspond with your table. It looks like Denver and Nairobi switched places in the table in comparison to the adjacency list.

**Comment by dvberkel** [comment]
Note that @RichardH18 created this excellent exercise

There were some discrepancies which I wanted to address in tonight video conference. We will discuss the question and answer and compare it to the [dijkstra](https://github.com/HAN-ASD-DT/exam-2018-2019/blob/dijkstra/algoritme.md) branch.

**Comment by dvberkel** [comment]
With pull request #3 this is resolved
