### ISSUE TITLE
Tentamen vragen

### ISSUE THREAD

**Issue by Dewinster** [HAN-ASD-DT/exam-2018-2019#13]
Is het mogelijk om de vragen in het "Nederlands" te formuleren?
Persoonlijk ben ik geen ster in talen, en tijdens het lezen van de PDFs gaat mij ook niet heel makkelijk af.

**Comment by titusvh** [comment]
Jusqu'à présent, tous les examens sont en néerlandais. Peut-être que c'est la norme chez HAN.

Je préfère aussi le néerlandais, qui lit beaucoup plus vite.

**Comment by titusvh** [comment]
Maar serieus:

Het lijkt erop dat in het ICA opleidingsstatuut alleen eisen worden gesteld aan de **Nederlandse** taal. Bij Engels staat zelfs "nvt".

Ik denk dat je dus mag aannemen dat het tentamen in het Nederlands is opgesteld.

**Comment by dvberkel** [comment]
Ik zal de tentamen vragen in het Nederlands opstellen
