### ISSUE TITLE
Presentaties wel/niet onderdeel van examen

### ISSUE THREAD

**Issue by titusvh** [HAN-ASD-DT/exam-2018-2019#14]
Ik ga uit dat als ik geen presentatie tot mijn beschikking heb het geen tentamenstof is.
Als dat niet klopt neem ik aan dat ik (lees: niet binnen een week van het tentamenmoment) op deze aanname wordt aangesproken...

In deze repo zie ik van de 12 presentaties alleen (in random order):
 * Swift (Dewin/Ties) (echter onleesbaar voor windowsgebruikers zoals ik)
 * Encryptie (Richard)
 * CIL (Titus)
 * Splay tree (Cor)

In een aparte repo
 * C (Jelle) (Geen presentatie maar alleen voorbeelden, dus een deel van de voorgestelde examenvragen worden niet gedekt!)

Edit:
Er zijn ook voorbeeldtentamenvragen over Fisher-Yates Shuffle gesteld, maar de theorie (presentatie) ontbreekt. Idem Huffmann. Tenzij die ook nog weer apart in de les als reguliere lesstof zijn behandeld. Maar hopelijk is er begrip dat het er niet overzichtelijke op wordt.

**Comment by dvberkel** [comment]
De vragen die nu in het tentamen zijn opgenomen zijn allemaal behandeld. Deze zullen dus ook onderdeel van het tentamen kunnen zijn.

Waar geen presentatie online bekend is zal geen examenvraag voor gemaakt worden.
