### ISSUE TITLE
Antwoord Fisher Yates vraag 3 mogelijk incorrect?

### ISSUE THREAD

**Issue by titusvh** [HAN-ASD-DT/exam-2018-2019#18]
Volgens mij klopt antwoord op 3 niet.

Mijns inziens slaat n op de gehele collectie, dan dus nog steeds O(n) omdat je de collectie 1x doorloopt.
Als je n toch als zijden vd matrix definieert (maar waarom zou je), dan is het n*n = n^2 en sowieso nooit n^n.

Klopt mijn redenatie?

**Comment by Dewinster** [comment]
Ik zou zeggen nˆ2, omdat je met een square grid (2d array) twee kanten op gaat.
Mochten een cube grid (3d array) zijn dan zou het nˆ3 worden, etc.

**Comment by dvberkel** [comment]
Het correct antwoord is inderdaad O(n^2). Omdat in een matrix van n bij n precies n^2 elementen zijn en de complexity van Fisher Yates O(aantal elementen) is.

**Comment by dvberkel** [comment]
@titusvh Het algoritme heeft dezelfde complexiteit, namelijk O(het aantal elementen dat wordt geschud). In het geval van een lijst is dat aantal n. Is een vierkante matrix van grootte n is dat n^2.

Wat er veranderd is waar n voor staat. In het ene geval is dat de lengte van de lijst, in de andere is dat de lengte van het aantal kolommen en rijen in de matrix.

**Comment by titusvh** [comment]
> @titusvh Het algoritme heeft dezelfde complexiteit, namelijk O(het aantal elementen dat wordt geschud). In het geval van een lijst is dat aantal n. Is een vierkante matrix van grootte n is dat n^2.
> 
> Wat er veranderd is waar n voor staat. In het ene geval is dat de lengte van de lijst, in de andere is dat de lengte van het aantal kolommen en rijen in de matrix.
@dvberkel 
Dat snap ik, maar dan klopt het antwoord op de vraag dus inderdaad niet, als de complexiteit niet verandert,  zoals je zelf aangeeft...

**Comment by titusvh** [comment]
En volgens mij zou het een goede gewoonte zijn dat de indiener een issue afsluit, omdat indiener zou moeten bepalen of issue naar zijn zin is afgehandeld...
