### ISSUE TITLE
Proefvragen architectuur

### ISSUE THREAD

**Issue by titusvh** [HAN-ASD-DT/exam-2018-2019#19]
We hebben nooit proeftentamens gehad bij ASD omdat de vragen in deze repo daarvoor zouden dienen.

Echter voor architectuur ontbreekt dit.

Ik heb dus geen goed idee welk soort vragen ik kan verwachten en dus op welke manier ik moet leren.

Bijvoorbeeld: "Wat vind Simon Brown de 5 belangrijkste aspecten aan Architecting?" Bij zo'n vraag is het feitjes stampen.
"Of wat zijn de 8 taken/rollen die Kruchten bij een architect vind horen?", idem.

Is het mogelijk (bijtijds) een paar voorbeeldvragen te krijgen, gezien het feit dat we geen proeftentamen hebben gehad? Om een beetje gevoel te krijgen van het soort vragen?

**Comment by WesselSlot** [comment]
Of zoiets als dit?
https://github.com/HAN-ASD-DT/exam-2018-2019/blob/Software-architecture/Software-Architecture.md

**Comment by titusvh** [comment]
> Of zoiets als dit?
> https://github.com/HAN-ASD-DT/exam-2018-2019/blob/Software-architecture/Software-Architecture.md

Ik heb geen idee wat voor soort vragen Daan voor ogen heeft en of deze daaronder valt.
Jouw vraag lijkt mij een zinvol voorbeeld van een vraag die ikzelf als docent zou kunnen stellen. Namelijk deels gebaseerd op feitenkennis maar ook beredeneerbaar.

Merk op dat de freeze is ingegaan dus vragen die wij nu zelf indienen geen onderdeel meer uitmaken van een tentamen.

**Comment by dvberkel** [comment]
Er staan een aantal vragen in [architecture.md](https://github.com/HAN-ASD-DT/exam-2018-2019/blob/master/architecture.md).

Andere mogelijke vragen zijn die zoals @RichardH18 aangeeft.

**Comment by dcswitzer** [comment]
@dvberkel wat bedoel je met de eerste vraag, definitie, ik zie niet direct een vraag staan, wel een definitie en antwoorden, maar zie niet direct wat de bedoeling is van die vraag
