### ISSUE TITLE
# 15 January

### ISSUE THREAD

**Issue by vinnie1234** [HAN-ASD-DT/exam-2018-2019#24]
No class

**Comment by vinnie1234** [comment]
Ha @dvberkel,

Ik dacht dat we vanavond de cijfers zouden doen en bespreken? Gezien vele met de Minor zitten en we niet heel veel dagen nog hebben + er nog kans moet zijn voor een herkansing + er nog presentaties zijn vind ik heel heel apart dat er **nog** een les uitvalt?

**Comment by Skudoku** [comment]
@dvberkel en na het tentamen van donderdag heb je ook nog toegezegd om assessment te doen met onder andere @Dewinster en ik, voor de casus.

**Comment by dvberkel** [comment]
Ik snap dat het vervelend is, maar ik realiseerde dat mensen in de gelegenheid moeten zijn om hun werk in te zien. Dat gaat slecht via video conferencing. Vandaar dat het de les is uitgevallen en dat het bespreken van het werk naar donderdag  is verplaatst.

**Comment by Dewinster** [comment]
@dvberkel 
Zou je mijn cijfer wel willen geven? Ik ben oprecht benieuwd.

**Comment by titusvh** [comment]
Ik ging er een beetje vanuit dat ik geen les meer had donderdag. En dat er alleen nog assessments zijn.

Meestal wordt eerst het cijfer verstrekt, en dan kunnen de mensen die nav cijfer behoefte hebben naar de inzage komen. Als ik het cijfer wel vast kan krijgen weet ik of ik behoefte heb aan inzage en of ik er speciaal voor naar school kom.

Overigens zijn er nog (minstens) 4 personen die een presentatie moeten geven.

For the record: ik heb dibbs op het allerlaatste tijdslot van mogelijk assessment :-)

**Comment by dvberkel** [comment]
@skudoku nee, jij kunt er van uit gaan dat jij in de gelegenheid gesteld word om het voorlopig cijfer te controleren.

**Comment by dvberkel** [comment]
@Dewinster De punten die jij hebt verzameld tijdens het tentamen
Architectuur: 46/50
Rest: 84/100
Bonus: 2

**Comment by dvberkel** [comment]
@titusvh Er is geen les.

Zoals je ondertussen wel weet ben ik niet zo van het *meestal*

Wat presentaties betreft is het de verantwoordelijkheid van die personen.

**Comment by WesselSlot** [comment]
@dvberkel Kun je dit niet voor iedereen doen?

**Comment by dvberkel** [comment]
@WesselSlot Ja, dat kan ik niet. Ik zal een upload doen van het overzicht. Dan kun jij het voor jezelf doen

**Comment by WesselSlot** [comment]
@dvberkel Dat is ook goed!

**Comment by maartenheebink** [comment]
@dvberkel, die upload zie ik dan ook graag

**Comment by dvberkel** [comment]
Ik heb de link geplaatst in het comment van 6 minuten geleden

**Comment by titusvh** [comment]
> @titusvh Er is geen les.
> 
> Zoals je ondertussen wel weet ben ik niet zo van het _meestal_

Haha, dat klopt. Maar soms is de gewoonte volgen niet perse een slecht idee 😁

> Wat presentaties betreft is het de verantwoordelijkheid van die personen.

Ok, dan neem ik aan dat ik het goed begrijp dat ik alleen nog naar school kom voor assessment en inzien tentamen als ik daar aanleiding voor zie.
