### ISSUE TITLE
Vragen over tentamen

### ISSUE THREAD

**Issue by titusvh** [HAN-ASD-DT/exam-2018-2019#9]
@dvberkel 
_Deels kopie van mail zodat antwoord ook voor de mensen te zien is die les(sen) missen._

Normaal hebben we meerdere tentamens van anderhalf uur. Nu worden twee tentamens gegeven ineens. Wordt dit een/één tentamen van 3u? Of een gebundeld tentamen van 1,5u?

Nadeel van 1,5u is dat elk onderdeel beperkt bevraagd wordt, en als je dan net één kennishiaatje hebt wordt je relatief zwaar gestraft. Bij ADB meegemaakt letterlijk 1 onderdeeltje kwam niet in "mijn" tekstuele lesstof voor [alleen in de video's] die wel voor 30% in het eindresultaat meetelde...)

Maak me wel ietwat zorgen over de hoeveelheid stof voor 1 tentamenmoment... 

Verder: tot welk moment is het zinvol om examenvragen in te leveren, als het examen eenmaal af is heeft het geen zin. En indien te laat dan is er weinig terugkoppeling mogelijk, bv als er fouten instaan.

Zelfde voor presentaties: welke presentaties doen nog mee als tentamenstof? Het lijkt mij reëel dat dit vóór de vakantie (lees: vrijdag a.s.) definitief is. En dat dan ook de eis is dat alle presentaties in onze repo staan! (Lees: niet in repo = geen examenstof = strafpunten presentator ;-)  ).

Samengevat dus:
* Hoe is tentanenvorm en duur
* Wanneer is deadline examenvragen
* Welke presentaties doen nog mee als tentamenstof
* (Keiharde) Deadline stellen voor indienen presentaties of indien niet hoe dan wel...

**Comment by jensdon** [comment]
+1 deze vragen zou ik ook graag beantwoord zien.

**Comment by dvberkel** [comment]
* De tentamenduur is gelijk aan de lesduur.
* Er zullen alleen tentamenvragen bij komen die behandeld zijn.
* Presentaties waar online materiaal beschikbaar is, of waar vragen in het college over behandeld zijn doen mee als tentamenstof.
* Zie punt twee en drie. Deadline is nu
